import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}){

  return (

    <ClerkProvider>
      
      <html lang="en" className='light'>
        <body className={cn('min-h-screen font-sans antialiased ', inter.className)}>
          <Navbar />
          {children}
        </body>
      </html>
    
    
    </ClerkProvider>
  )
}
